name: 'AWS Testing'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::631973159338:role/sts-lab-2-target
          role-session-name: OIDCSession

      - name: List IAM Roles
        run: aws iam list-roles
        shell: bash

      - name: List Secrets in AWS Secrets Manager
        run: aws secretsmanager list-secrets
        shell: bash

      - name: List Assume Tokens
        run: aws sts get-caller-identity
        shell: bash

      - name: List Assume Tokens
        run: aws iam list-attached-role-policies --role-name sts-lab-2-target
        shell: bash

      - name: List Assume Tokens
        run: aws sts assume-role-with-web-identity --role-arn "arn:aws:iam::631973159338:role/sts-lab-2-target" --role-session-name "github-actions" --web-identity-token $ACTIONS_ID_TOKEN_REQUEST_TOKEN --duration-seconds 900
        shell: bash

        
